import { formatDateForDoc } from "src/helpers/formtDate";
import { sgdeaAxios } from "src/services";

//********************************** */
export const selectOptionReportes = [
  { label: 'Consulta general ', id: 1 },
  { label: 'Expediente', id: 2 },
  { label: 'Medicina Laboral', id: 3 },
  { label: 'PQRD', id: 4 },
  { label: 'Superintendencia', id: 5 },
  { label: 'Entes de Control', id: 6 },
  { label: 'Tutelas', id: 7 },
  { label: 'Facturas administrativas', id: 8 },
  { label: 'Emisión de factura', id: 9 },
  { label: 'Usuarios', id: 10 },
]

export const selectOptionTipoReportes = [
  { label: 'Devoluciones', id: 1 },
  { label: 'Entradas', id: 2 },
  { label: 'Internos', id: 3 },
  { label: 'Reasignaciones', id: 4 },
  { label: 'Reporte de observaciones radicados', id: 5 },
  { label: 'Salida', id: 6 },
  { label: 'Seguimiento comunicación de salida', id: 7 },
]

// export const selectOptionCanalEnvio = [
//   { label: 'Todos', id: 1 },
//   { label: 'Personal', id: 2 },
//   { label: 'Mensajero', id: 3 },
//   { label: 'Correo electrónico', id: 4 },
//   { label: 'Correo electrónico certificado', id: 5 },
//   { label: 'Courier', id: 6 },
// ]

// export const selectOptionCanalRadicacion = [
//   { label: 'Todos', id: 1 },
//   { label: 'Ventanilla', id: 2 },
//   { label: 'Contact Center', id: 3 },
//   { label: 'MAIL', id: 4 },
//   { label: 'WEB ANÓNIMO', id: 5 },
//   { label: 'WEB SERVICE', id: 6 },
//   { label: 'WEB DEFENDOR', id: 7 },
//   { label: 'WEB MEDICINA LABORAL', id: 8 },
// ]

export const selectOptionEstado = [
  // Estados en bd
  { label: 'Todos', id: null },
  { label: 'En Edición', id: 4 },
  { label: 'Por Aprobar', id: 8 },

  { label: 'Radicado', id: 2 },
  { label: 'Radicado Web', id: 3 },
  { label: 'Proceso Finalizado', id: 21 },
  { label: 'Aceptado', id: 5 },
  { label: 'Anulado en Gestión', id: 6 },
  { label: 'Anulado en Radicación', id: 7 },
  { label: 'Validación de Información', id: 22 },
  { label: 'Transferido', id: 9 },
  { label: 'Pendiente por Asignar Área', id: 10 },
  { label: 'Por Asignar oficina', id: 11 },
  { label: 'Oficina Asignada', id: 12 },
  { label: 'Devuelto por Reasignar Oficina', id: 13 },
  { label: 'En tipificación', id: 14 },
  { label: 'Por Enviar Extracción', id: 15 },
  { label: 'Oficina Asignada Facturas', id: 16 },
  { label: 'Asignado para Gestión', id: 17 },
  { label: 'Facturas Asignado para Gestión', id: 18 },
  { label: 'Radicado', id: 19 },
  { label: 'Por Radicar', id: 23 },
  { label: 'Radicación', id: 24 },
  { label: 'Asignado', id: 25 },
  { label: 'Cerrado en Término', id: 26 },
  { label: 'Consolidado', id: 27 },
  { label: 'Rechazado de Aprobación', id: 28 },
  { label: 'En Extracción', id: 29 },
  { label: 'Pendiente por Incluir a Expediente', id: 30 },
  { label: 'Por Radicar Ventanilla', id: 31 },
  { label: 'Gestión Manual', id: 32 },
  { label: 'Validación UID', id: 33 },
  { label: 'Cierre Documento Informativo', id: 34 },
  { label: 'Por Revisión', id: 35 },
  { label: 'Rechazado por Revisor', id: 36 },
  { label: 'Revisado Por Consolidar', id: 37 },
  { label: 'Pendiente Completar Datos', id: 38 },
  { label: 'Radicando Mail', id: 39 },
  { label: 'Pendiente Control de Calidad', id: 40 },
  { label: 'Control de Calidad', id: 41 },
  { label: 'Incluido a Expediente', id: 42 },
  { label: 'Constancia de Ejecutoriedad', id: 43 },
]

export const selectOptionTipoTrimite = [
  { label: 'Todos', id: 1 },
  { label: 'Correspondencia', id: 2 },
  { label: 'PQRD', id: 3 },
  { label: 'Tutelas', id: 4 },
  { label: 'Facturas Administrativas', id: 5 },
  { label: 'Cuentas de Cobro', id: 6 },
  { label: 'Procesos Jurídicos', id: 7 },
  { label: 'Requerimientos Entes de Control', id: 8 },
  { label: 'Retiro de Empresa', id: 9 },
  { label: 'Informativos', id: 10 },
  { label: 'Contratos', id: 11 },
  { label: 'MORTALES', id: 12 },
  { label: 'Recepción Documental', id: 13 },
  { label: 'Medicina Laboral', id: 14 },
]
//********************************** */

export const columnsReportesUsers: any = [
  {
    name: "codigoUsuario",
    label: "Código del Usuario",
    field: "codigoUsuario",
    sortable: true,
  },
  {
    name: "tipoUsuario",
    label: "Tipo Usuario",
    field: "tipoUsuario",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoDocumento",
    label: "Tipo Documento",
    field: row => row.tipoDocumento || "-",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroDocumento",
    label: "Número de Documento de Identificación",
    field: "numeroDocumento",
    sortable: true,
    align: "center",
  },
  {
    name: "nombreApellidos",
    label: "Nombre y Apellidos",
    field: "nombreApellidos",
    sortable: true,
    align: "center",
  },
  {
    name: "correoElectronico",
    label: "Correo Electrónico",
    field: "correoElectronico",
    sortable: true,
    align: "center",
  },

  {
    name: "cargo",
    label: "Cargo",
    field: "cargo",
    sortable: true,
    align: "center",
  },
  {
    name: "oficina",
    label: "Oficina",
    field: "oficina",
    sortable: true,
    align: "center",
  },
  {
    name: "oficinaEstado",
    label: "Oficina - Estado",
    field: row => row.oficinaEstado || "inactivo",
    sortable: true,
    align: "center",
  },
  {
    name: "perfil",
    label: "Perfil",
    field: "perfil",
    sortable: true,
    align: "center",
  },
  {
    name: "correoCertificadoGestionador",
    label: "Correo Certificado ( Gestionador ) Si/No",
    field: row => row.correoCertificadoGestionador || "No",
    sortable: true,
    align: "center",
  },
  {
    name: "consolida",
    label: "Consolida",
    field: "consolida",
    sortable: true,
    align: "center",
  },
  {
    name: "punto",
    label: "Punto",
    field: row => row.punto || "-",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaCreacionUsuario",
    label: "Fecha Creacin Usuario",
    field: (row) => row.fechaCreacionUsuario,
    sortable: true,
    align: "center",
  },
  {
    name: "mesCreacionUsuario",
    label: "Mes Creación de Usuario",
    field: "mesCreacionUsuario",
    sortable: true,
    align: "center",
  },
  {
    name: "ultimaFechaAcceso",
    label: "Última Fecha Acceso",
    field: (row) => row.ultimaFechaAcceso || '-',
    sortable: true,
    align: "center",
  },
  {
    name: "estado",
    label: "Estado",
    field: "estado",
    sortable: true,
    align: "center",
  },
  {
    name: "causaUltimaInactivacion",
    label: "Causa de Última Inactivación",
    field: row => row.causaUltimaInactivacion || "-",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaUltimaInactivacion",
    label: "Fecha de Última  Inactivación",
    field: (row) => row.fechaUltimaInactivacion,
    sortable: true,
    align: "center",
  },
  {
    name: "ultimaModificacion",
    label: "Última Modificación",
    field: (row) => row.ultimaModificacion,
    sortable: true,
    align: "center",
  },
  {
    name: "fechaModificacion",
    label: "Fecha de la Modificación",
    field: (row) => row.fechaModificacion,
    sortable: true,
    align: "center",
  },
  {
    name: "usuarioModificacion",
    label: "Usuario Modificación",
    field: row => row.usuarioModificacion || "-",
    sortable: true,
    align: "center",
  },
];

export const columnsDevoluciones: any = [
  {
    name: "numeroRadicadoSalida",
    label: "Número de Radicado",
    align: "center",
    field: (row: any) => row.numeroRadicadoSalida,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreDestinatario",
    label: "Nombre del Destinatario",
    align: "center",
    field: (row: any) => row.nombreDestinatario,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "originalCopia",
    label: "Original / Copia",
    align: "center",
    field: (row: any) => row.originalCopia,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "canalRadicacion",
    label: "Canal de Envio",
    headerStyle: "min-width:130px;",
    align: "center",
    field: (row: any) => row.canalEnvio,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "direccionCorreoElectronico",
    label: "Dirección de Correo Electronico",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.direccionCorreoElectronico,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "direccionEnvioFisico",
    label: "Dirección Envío Físico",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.direccionEnvioFisico,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroGuia",
    label: "Número de Guía",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.numeroGuia,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreGestionador",
    label: "Nombre del Gestionador",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.nombreGestionador,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "dependencia",
    label: "Dependencia",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.dependencia,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoTramite",
    label: "Tipo de Trámite",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.tipoTramite,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estado",
    label: "Estado",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.estado,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroRadicadoOrigen",
    label: "Número de radicado origen",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.numeroRadicadoOrigen,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramiteRadicadoOrigen",
    label: "Trámite de radicado origen",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.tramiteRadicadoOrigen,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobador",
    label: "Aprobador",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.aprobador,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha de radicación",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaRadicacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "fechaRecibidoCorrespondencia",
    label: "Fecha de Recibido en Correspondencia",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaRecibidoCorrespondencia,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "fechaDevolucion",
    label: "Fecha de devolución",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaDevolucion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "fechaMaximaRespuesta",
    label: "Fecha Máxima de Respuesta",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaMaximaRespuesta,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "fechaInicioGestion",
    label: "Fecha de Iniciar Gestión",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaIniciarGestion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "fechaCierre",
    label: "Fecha de Cierre",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaCierre,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
  {
    name: "accion",
    label: "Acción",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.accion,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroDevolucion",
    label: "Nro. Devolución",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.numeroDevolucion,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "publicado",
    label: "Publicado",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.publicado,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroActaDesfijacion",
    label: "Número de Acta de Desfijación",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.numeroActaDesfijacion,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaActaDesfijacion",
    label: "Fecha Acta de Desfijación",
    headerStyle: "min-width:150px;",
    align: "center",
    field: (row: any) => row.fechaActaDesfijacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : val;
    },
    sortable: true,
  },
];

export const columnsEntradas: any = [
  {
    name: "nroRadicado",
    label: "Número de Radicado",
    align: "center",
    field: (row: any) => row.numeroRadicado,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "oficinaAsignada",
    label: "Oficina asignada",
    align: "center",
    field: (row: any) => row.oficinaAsignada,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoTramite",
    label: "Tipo de trámite",
    align: "center",
    field: (row: any) => row.tipoTramite, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoRequerimientoEnteControl",
    label: "Tipo Requerimiento Ente de Control",
    align: "center",
    field: (row: any) => row.tipoRequerimientoEnteDeControl,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estado",
    label: "Estado",
    align: "center",
    field: (row: any) => row.estado,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "canalRadicacion",
    label: "Canal Radicación",
    align: "center",
    field: (row: any) => row.canalRadicacion,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "sucursal",
    label: "Sucursal",
    align: "center",
    field: (row: any) => row.sucursal, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "puntoRadicacion",
    label: "Punto de Radicación",
    align: "center",
    field: (row: any) => row.punto,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha Radicación",
    align: "center",
    field: (row: any) => row.fechaRadicacion, //*
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "mes",
    label: "Mes",
    align: "center",
    field: (row: any) => row.mes,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "docRemitente",
    label: "Doc. Remitente",
    align: "center",
    field: (row: any) => row.docRemitente,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreRemitente",
    label: "Nombre del Remitente",
    align: "center",
    field: (row: any) => row.nombreDelRemitente,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "usuarioGestion",
    label: "Usuario Gestión",
    align: "center",
    field: (row: any) => row.usuarioGestion, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "direccionRemitente",
    label: "Dirección Remitente",
    align: "center",
    field: (row: any) => row.direccionRemitente, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "telefonoRemitente",
    label: "Teléfono Remitente",
    align: "center",
    field: (row: any) => row.telefonoRemitente,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoRemitente",
    label: "Correo Remitente",
    align: "center",
    field: (row: any) => row.correoRemitente,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "departamentoRemitente",
    label: "Departamento Remitente",
    align: "center",
    field: (row: any) => row.departamentoRemitente, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "municipioRemitente",
    label: "Municipio Remitente",
    align: "center",
    field: (row: any) => row.municipioRemitente, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "documentoAfectado",
    label: "Documento Afectado",
    align: "center",
    field: (row: any) => row.documentoAfectado, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreAfectado",
    label: "Nombre Afectado",
    align: "center",
    field: (row: any) => row.nombreAfectado, //*
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "anexos",
    label: "Anexos",
    align: "center",
    field: (row: any) => row.anexos,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "folios",
    label: "Folios",
    align: "center",
    field: (row: any) => row.folios,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicador",
    label: "Radicador",
    align: "center",
    field: (row: any) => row.radicador,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoSalida",
    label: "Radicado de Salida",
    align: "center",
    field: (row: any) => row.radicadoDeSalida,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "medioEnvio",
    label: "Medio de Envío",
    align: "center",
    field: (row: any) => row.medioDeEnvio,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroGuia",
    label: "Número de Guía",
    align: "center",
    field: (row: any) => row.numeroDeGuia,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estadoGuia",
    label: "Estado de Guía",
    align: "center",
    field: (row: any) => row.estadoDeGuia,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoElectronicoEnvio",
    label: "Correo Electrónico de Envío",
    align: "center",
    field: (row: any) => row.correoElectronicoDeEnvio,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "revisor",
    label: "Revisor",
    align: "center",
    field: (row: any) => row.revisor,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobador",
    label: "Aprobador",
    align: "center",
    field: (row: any) => row.aprobador,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramiteInicial",
    label: "Trámite Inicial",
    align: "center",
    field: (row: any) => row.tramiteInicial,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoFirma",
    label: "Tipo de Firma",
    align: "center",
    field: (row: any) => row.tipoDeFirma,
    format: (val: string) => (val === null || val == "" ? "-" : val),
    sortable: true,
  },
];

export const columnsInternos: any = [
  {
    name: "numeroRadicado",
    label: "Número Radicado",
    align: "center",
    field: (row: any) => row.numeroRadicado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha Radicación",
    align: "center",
    field: (row: any) => row.fechaRadicacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "mesRadicacion",
    label: "Mes Radicación",
    align: "center",
    field: (row: any) => row.mesRadicacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "dependenciaOrigen",
    label: "Dependencia Origen",
    align: "center",
    field: (row: any) => row.dependenciaOrigen,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobador",
    label: "Aprobador",
    align: "center",
    field: (row: any) => row.aprobador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "dependenciaDestino",
    label: "Dependencia Destino",
    align: "center",
    field: (row: any) => row.dependenciaDestino,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "usuario",
    label: "Usuario",
    align: "center",
    field: (row: any) => row.usuario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoElectronicoDestinatario",
    label: "Correo Electrónico Destinatario",
    align: "center",
    field: (row: any) => row.correoElectronicoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "copias",
    label: "Copias",
    align: "center",
    field: (row: any) => row.copias,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreAfectado",
    label: "Nombre Afectado",
    align: "center",
    field: (row: any) => row.nombreAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoDocumentoAfectado",
    label: "Tipo Documento Afectado",
    align: "center",
    field: (row: any) => row.tipoDocumentoAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "identificacionAfectado",
    label: "Identificación Afectado",
    align: "center",
    field: (row: any) => row.identificacionAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "folios",
    label: "Folios",
    align: "center",
    field: (row: any) => row.folios,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "anexos",
    label: "Anexos",
    align: "center",
    field: (row: any) => row.anexos,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asunto",
    label: "Asunto",
    align: "center",
    field: (row: any) => row.asunto,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estado",
    label: "Estado",
    align: "center",
    field: (row: any) => row.estado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "gestionador",
    label: "Gestionador",
    align: "center",
    field: (row: any) => row.gestionador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicador",
    label: "Radicador",
    align: "center",
    field: (row: any) => row.radicador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "medioEnvio",
    label: "Medio de Envío",
    align: "center",
    field: (row: any) => row.medioDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "guiaEnvio",
    label: "# Guía de Envío",
    align: "center",
    field: (row: any) => row.numeroGuiaDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
]

export const columnsReasignaciones: any = [
  {
    name: "numeroRadicadoENT",
    label: "Número de Radicado ENT",
    align: "center",
    field: (row: any) => row.numeroRadicadoEntrada,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha de Radicación",
    align: "center",
    field: (row: any) => row.fechaRadicacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "canalRadicacion",
    label: "Canal de Radicación",
    align: "center",
    field: (row: any) => row.canalRadicacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "sucursal",
    label: "Sucursal",
    align: "center",
    field: (row: any) => row.sucursal,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "puntoRadicacion",
    label: "Punto de Radicación",
    align: "center",
    field: (row: any) => row.puntoRadicacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicador",
    label: "Radicador",
    align: "center",
    field: (row: any) => row.radicador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "oficinaRadicador",
    label: "Oficina Radicador",
    align: "center",
    field: (row: any) => row.oficinaRadicador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramiteInicial",
    label: "Trámite (Inicial)",
    align: "center",
    field: (row: any) => row.tramiteInicial,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "oficinaGestionInicial",
    label: "Oficina Asignada para Gestión (Inicial)",
    align: "center",
    field: (row: any) => row.oficinaInicialAsignada,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asignadorResponsableInicial",
    label: "Asignador de Responsable Oficina Asignada (Inicial)",
    align: "center",
    field: (row: any) => row.asignadorOficinaInicialAsignada,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "conteoReasignaciones",
    label: "Conteo (#) de Reasignaciones (Cambio de Oficina)",
    align: "center",
    field: (row: any) => row.conteoReasignaciones,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaReasignacionFinal",
    label: "Fecha de Reasignación Oficina (Final)",
    align: "center",
    field: (row: any) => row.fechaReasignacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "oficinaResponsableFinal",
    label: "Oficina Responsable de Respuesta (Final)",
    align: "center",
    field: (row: any) => row.oficinaResponsableRespuesta,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramiteFinal",
    label: "Trámite (Final)",
    align: "center",
    field: (row: any) => row.tramiteFinal,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tiempoAsignacionFinal",
    label: "Tiempo Asignación de Radicación a Oficina Responsable (Final)",
    align: "center",
    field: (row: any) => row.tiempoAsignacionRadicacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asignadorResponsableFinal",
    label: "Asignador de Responsable (Final)",
    align: "center",
    field: (row: any) => row.asignadorDeResponsable,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaAsignacionGestionadorFinal",
    label: "Fecha de Asignación al Gestionador (Final)",
    align: "center",
    field: (row: any) => row.fechaAsignacionGestionador,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "gestionadorResponsableFinal",
    label: "Gestionador Responsable (Final)",
    align: "center",
    field: (row: any) => row.gestionadorResponsable,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "gestionadoresIntervienenFinal",
    label: "Gestionadores que Intervienen en la Respuesta (Final)",
    align: "center",
    field: (row: any) => row.gestionadoresRespuesta,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaIniciarGestion",
    label: "Fecha de Iniciar Gestión",
    align: "center",
    field: (row: any) => row.fechaInicioGestion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "procesoGestionador",
    label: "Proceso (Gestionador)",
    align: "center",
    field: (row: any) => row.proceso,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "causaRaizGestionador",
    label: "Causa-Raíz (Gestionador)",
    align: "center",
    field: (row: any) => row.causaRaiz,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aFavorGestionador",
    label: "A Favor de (Gestionador)",
    align: "center",
    field: (row: any) => row.aFavorDe,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreProveedorGestionador",
    label: "Nombre del Proveedor (Gestionador)",
    align: "center",
    field: (row: any) => row.nombreProveedor,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreAprobador",
    label: "Nombre Aprobador",
    align: "center",
    field: (row: any) => row.nombreAprobador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoSalida",
    label: "Radicado de Salida",
    align: "center",
    field: (row: any) => row.numeroRadicadoSalida,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "destinatarioPrincipal",
    label: "Destinatario Principal",
    align: "center",
    field: (row: any) => row.destinatarioPrincipal,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  }
]

export const columnsReposteObservaciones = [
  {
    name: "radicado",
    label: "Radicado",
    align: "center",
    field: (row: any) => row.radicado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "usuario",
    label: "Usuario",
    align: "center",
    field: (row: any) => row.usuario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "oficina",
    label: "Oficina",
    align: "center",
    field: (row: any) => row.oficina,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "accion",
    label: "Acción",
    align: "center",
    field: (row: any) => row.accion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaAccion",
    label: "Fecha de la Acción",
    align: "center",
    field: (row: any) => row.fechaAccion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "observacion",
    label: "Observación",
    align: "center",
    field: (row: any) => row.observacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "detalleObservacion",
    label: "Detalle de la Observación",
    align: "center",
    field: (row: any) => row.detalleObservacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  }
];

export const columnsSalida: any = [
  {
    name: "numeroRadicado",
    label: "Número Radicado",
    align: "center",
    field: (row: any) => row.numeroRadicado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "copia",
    label: "Copia",
    align: "center",
    field: (row: any) => row.copia,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoAnterior",
    label: "Radicado Anterior",
    align: "center",
    field: (row: any) => row.radicadoAnterior,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha Radicación",
    align: "center",
    field: (row: any) => row.fechaRadicacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "mes",
    label: "Mes",
    align: "center",
    field: (row: any) => row.mes,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoEntrada",
    label: "Radicado Entrada",
    align: "center",
    field: (row: any) => row.radicadoEntrada,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "destinatario",
    label: "Destinatario",
    align: "center",
    field: (row: any) => row.destinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoDocumentoDestinatario",
    label: "Tipo Documento Destinatario",
    align: "center",
    field: (row: any) => row.tipoDocumentoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroDocumentoDestinatario",
    label: "Número Documento Destinatario",
    align: "center",
    field: (row: any) => row.numeroDocumentoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "direccionDestinatario",
    label: "Dirección Destinatario",
    align: "center",
    field: (row: any) => row.direccionDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "telefonoDestinatario",
    label: "Teléfono Destinatario",
    align: "center",
    field: (row: any) => row.telefonoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "departamentoDestinatario",
    label: "Departamento Destinatario",
    align: "center",
    field: (row: any) => row.departamentoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "codigoDepartamentoDestinatario",
    label: "Código Departamento Destinatario (Código DIVIPOLA)",
    align: "center",
    field: (row: any) => row.codigoDepartamentoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "municipioDestinatario",
    label: "Municipio Destinatario",
    align: "center",
    field: (row: any) => row.municipioDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "codigoMunicipioDestinatario",
    label: "Código Municipio Destinatario (Código DIVIPOLA)",
    align: "center",
    field: (row: any) => row.codigoMunicipioDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramite",
    label: "Trámite",
    align: "center",
    field: (row: any) => row.tramite,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "cantidadFolios",
    label: "Cantidad de Folios",
    align: "center",
    field: (row: any) => row.cantidadDeFolios,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "anexos",
    label: "Anexos",
    align: "center",
    field: (row: any) => row.anexos,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asunto",
    label: "Asunto",
    align: "center",
    field: (row: any) => row.asunto,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobacionMasiva",
    label: "Aprobación Masiva",
    align: "center",
    field: (row: any) => row.aprobacionMasiva,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estado",
    label: "Estado",
    align: "center",
    field: (row: any) => row.estado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estadoSalida",
    label: "Estado Salida",
    align: "center",
    field: (row: any) => row.estadoSalida,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRecibidoCorrespondencia",
    label: "Fecha Recibido en Correspondencia",
    align: "center",
    field: (row: any) => row.fechaRecibidoEnCorrespondencia,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "tipoDocumentoAfectado",
    label: "Tipo Documento Afectado",
    align: "center",
    field: (row: any) => row.tipoDocumentoAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroDocumentoAfectado",
    label: "Número Documento Afectado",
    align: "center",
    field: (row: any) => row.numeroDocumentoAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreAfectado",
    label: "Nombre Afectado",
    align: "center",
    field: (row: any) => row.nombreAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "dependenciaQueEnvía",
    label: "Dependencia que Envía",
    align: "center",
    field: (row: any) => row.dependenciaQueEnvía,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobador",
    label: "Aprobador",
    align: "center",
    field: (row: any) => row.aprobador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "gestionador",
    label: "Gestionador",
    align: "center",
    field: (row: any) => row.gestionador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicador",
    label: "Radicador",
    align: "center",
    field: (row: any) => row.radicador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "guiaEnvio",
    label: "# Guía de Envío",
    align: "center",
    field: (row: any) => row.guiaDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estadoGuia",
    label: "Estado Guía",
    align: "center",
    field: (row: any) => row.estadoGuia,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "medioEnvio",
    label: "Medio de Envío",
    align: "center",
    field: (row: any) => row.medioDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoDestinatario",
    label: "Correo del Destinatario",
    align: "center",
    field: (row: any) => row.correoDelDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "idEnvioSealmail",
    label: "ID Envío Sealmail",
    align: "center",
    field: (row: any) => row.idEnvioSealmail,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "eventoSealmail",
    label: "Evento Sealmail",
    align: "center",
    field: (row: any) => row.eventoSealmail,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "accion",
    label: "Acción",
    align: "center",
    field: (row: any) => row.accion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "guiaEnvioDevolucion",
    label: "# Guía de Envío Devolución",
    align: "center",
    field: (row: any) => row.guiaDeEnvioDevolucion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoDestinatarioDevolucion",
    label: "Correo del Destinatario Devolución",
    align: "center",
    field: (row: any) => row.correoDelDestinatarioDevolucion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroDevolucion",
    label: "Nro. Devolución",
    align: "center",
    field: (row: any) => row.nroDevolucion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "publicacion",
    label: "Publicación",
    align: "center",
    field: (row: any) => row.publicacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "cuentaEnvioCorreo",
    label: "Cuenta Envío del Correo",
    align: "center",
    field: (row: any) => row.cuentaEnvioDelCorreo,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoFirma",
    label: "Tipo de Firma",
    align: "center",
    field: (row: any) => row.tipoDeFirma,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  }
];

export const columnsComunicacionSalida: any = [
  {
    name: "consecutivoCreacion",
    label: "Consecutivo de Creación",
    align: "center",
    field: (row: any) => row.consecutivoCreacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaCreacion",
    label: "Fecha de Creación",
    align: "center",
    field: (row: any) => row.fechaCreacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "gestionador",
    label: "Gestor",
    align: "center",
    field: (row: any) => row.gestionador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "dependenciaEnvio",
    label: "Dependencia que Envía",
    align: "center",
    field: (row: any) => row.dependenciaEnvia,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estado",
    label: "Estado",
    align: "center",
    field: (row: any) => row.estado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "expediente",
    label: "Expediente",
    align: "center",
    field: (row: any) => row.expediente,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "destinatario",
    label: "Destinatario",
    align: "center",
    field: (row: any) => row.destinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "direccionDestinatario",
    label: "Dirección Destinatario",
    align: "center",
    field: (row: any) => row.destinatarioDireccion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "telefonoDestinatario",
    label: "Teléfono Destinatario",
    align: "center",
    field: (row: any) => row.destinatarioTelefono,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "departamentoDestinatario",
    label: "Departamento Destinatario",
    align: "center",
    field: (row: any) => row.destinatarioDepartamento,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "municipioDestinatario",
    label: "Municipio Destinatario",
    align: "center",
    field: (row: any) => row.destinatarioMunicipio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tramiteCantidadFolios",
    label: "Trámite Cantidad de Folios",
    align: "center",
    field: (row: any) => row.cantidadFolios,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "anexos",
    label: "Anexos",
    align: "center",
    field: (row: any) => row.anexos,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asunto",
    label: "Asunto",
    align: "center",
    field: (row: any) => row.asunto,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobacionMasiva",
    label: "Aprobación Masiva",
    align: "center",
    field: (row: any) => row.aprobacionMasiva,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoAnterior",
    label: "Radicado Anterior",
    align: "center",
    field: (row: any) => row.radicadoAnterior,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "prefijo",
    label: "Prefijo",
    align: "center",
    field: (row: any) => row.prefijo,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "tipoDocumentoAfectado",
    label: "Tipo Documento Afectado",
    align: "center",
    field: (row: any) => row.tipoDocumentoAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroDocumentoAfectado",
    label: "Número Documento Afectado",
    align: "center",
    field: (row: any) => row.numeroDocumentoAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "nombreAfectado",
    label: "Nombre Afectado",
    align: "center",
    field: (row: any) => row.nombreAfectado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRechazo",
    label: "Fecha Rechazo",
    align: "center",
    field: (row: any) => row.fechaRechazo,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "responsableRechazo",
    label: "Responsable de Rechazo",
    align: "center",
    field: (row: any) => row.responsableDeRechazo,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaEnvioAprobacion",
    label: "Fecha Envío de Aprobación",
    align: "center",
    field: (row: any) => row.fechaEnvioAprobacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "responsableAprobacion",
    label: "Responsable de Aprobación",
    align: "center",
    field: (row: any) => row.responsableAprobacion,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "aprobador",
    label: "Aprobador",
    align: "center",
    field: (row: any) => row.aprobador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaAprobacion",
    label: "Fecha de Aprobación",
    align: "center",
    field: (row: any) => row.fechaAprobacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "copia",
    label: "Copia",
    align: "center",
    field: (row: any) => row.tipoCopia,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRadicacion",
    label: "Fecha Radicación",
    align: "center",
    field: (row: any) => row.fechaRadicacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "radicador",
    label: "Radicador",
    align: "center",
    field: (row: any) => row.radicador,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "radicadoEntrada",
    label: "Radicado Entrada",
    align: "center",
    field: (row: any) => row.radicadorEntrada,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "asignadoPor",
    label: "Asignado Por",
    align: "center",
    field: (row: any) => row.asignadoPor,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "estadoSalida",
    label: "Estado Salida",
    align: "center",
    field: (row: any) => row.estadoSalida,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaRecibidoCorrespondencia",
    label: "Fecha Recibido en Correspondencia",
    align: "center",
    field: (row: any) => row.fechaRecibidoCorrespondencia,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  },
  {
    name: "guiaEnvioEstadoGuia",
    label: "# Guía de Envío Estado Guía",
    align: "center",
    field: (row: any) => row.numeroGuiaDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "medioEnvio",
    label: "Medio de Envío",
    align: "center",
    field: (row: any) => row.medioDeEnvio,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "idEnvioSealmail",
    label: "ID Envío Sealmail",
    align: "center",
    field: (row: any) => row.idEnvioSealmail,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "eventoSealmail",
    label: "Evento Sealmail",
    align: "center",
    field: (row: any) => row.eventoSealmail,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "correoDestinatario",
    label: "Correo del Destinatario",
    align: "center",
    field: (row: any) => row.correoDestinatario,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "publicado",
    label: "Publicado (Sí/No)",
    align: "center",
    field: (row: any) => row.publicado,
    format: (val: string) => (val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "numeroActaDesfijacion",
    label: "Número de Acta de Desfijación",
    align: "center",
    field: (row: any) => row.numeroDeActaDeDesfijacio || '-',
    format: (val: string) => (val === null || val === null || val === "" ? "-" : val),
    sortable: true,
  },
  {
    name: "fechaActaDesfijacion",
    label: "Fecha Acta de Desfijación",
    align: "center",
    field: (row: any) => row.fechaDeActaDeDesfijacion,
    format: (val: string) => {
      return val === null || val === ""  ? "-" : formatDateForDoc(val);
    },
    sortable: true,
  }
];
