export const REPORTES_HEADER = [
  {
    name: "idRadicado",
    label: "Número de radicado".toUpperCase(),
    field: "idRadicado",
    sortable: true,
    align: "center",
  },
  {
    name: "fecha",
    label: "Fecha de radicado".toUpperCase(),
    field: "fechaR",
    sortable: true,
    align: "center",
  },
  {
    name: "fecha",
    label: "Fecha máxima de respuesta".toUpperCase(),
    field: "fechaM",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaCierre",
    label: "Fecha de cierre".toUpperCase(),
    field: "fechaCierre",
    sortable: true,
    align: "center",
  },
  {
    name: "fecha",
    label: "Fecha de envío".toUpperCase(),
    field: "fechaE",
    sortable: true,
    align: "center",
  },
  {
    name: "tiempo",
    label: "Tiempo por vencer".toUpperCase(),
    field: "tiempoV",
    sortable: true,
    align: "center",
  },
  {
    name: "canal",
    label: "Canal de radicación".toUpperCase(),
    field: "canal",
    sortable: true,
    align: "center",
  },
  {
    name: "detalleTramite",
    label: "Detalle del trámite".toUpperCase(),
    field: "detalleTramite",
    sortable: true,
    align: "center",
  },
  {
    name: "estado",
    label: "Estado".toUpperCase(),
    field: "estado",
    sortable: true,
    align: "center",
  },
  {
    name: "radicador",
    label: "Radicador".toUpperCase(),
    field: "radicador",
    sortable: true,
    align: "center",
  },
  {
    name: "oficinaRespuesta",
    label: "Oficina responsable de respuesta".toUpperCase(),
    field: "oficinaRespuesta",
    sortable: true,
    align: "center",
  },
  {
    name: "tiempoAsignacion",
    label: "Tiempo asignación de radicación a oficina responsable".toUpperCase(),
    field: "tiempoAsignacion",
    sortable: true,
    align: "center",
  },
  {
    name: "asignador",
    label: "Asignador de responsable".toUpperCase(),
    field: "asignador",
    sortable: true,
    align: "center",
  },
  {
    name: "revisor",
    label: "Revisor".toUpperCase(),
    field: "revisor",
    sortable: true,
    align: "center",
  },
  {
    name: "proceso",
    label: "Proceso".toUpperCase(),
    field: "proceso",
    sortable: true,
    align: "center",
  },
  {
    name: "subproceso",
    label: "Subproceso".toUpperCase(),
    field: "subproceso",
    sortable: true,
    align: "center",
  },
  {
    name: "formatoTiempo",
    label: "Formato tiempo".toUpperCase(),
    field: "formatoTiempo",
    sortable: true,
    align: "center",
  },
  {
    name: "tiempoDefinido",
    label: "Tiempo definido".toUpperCase(),
    field: "tiempoDefinido",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaAsignacionOficina",
    label: "Fecha de asignación a la oficina".toUpperCase(),
    field: "fechaAsignacionOficina",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaAsignacionGestionador",
    label: "Fecha de asignación al gestionador".toUpperCase(),
    field: "fechaAsignacionGestionador",
    sortable: true,
    align: "center",
  },
  {
    name: "diasAsignacionGestionador",
    label: "Días de asignación del gestionador".toUpperCase(),
    field: "diasAsignacionGestionador",
    sortable: true,
    align: "center",
  },
  {
    name: "gestionador",
    label: "Gestionador".toUpperCase(),
    field: "gestionador",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaIniciarGestion",
    label: "Fecha de iniciar gestión".toUpperCase(),
    field: "fechaIniciarGestion",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoSolicitud",
    label: "Tipo solicitud".toUpperCase(),
    field: "tipoSolicitud",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoTramite",
    label: "Tipo trámite".toUpperCase(),
    field: "tipoTramite",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroSiniestro",
    label: "Número de siniestro".toUpperCase(),
    field: "numeroSiniestro",
    sortable: true,
    align: "center",
  },
  {
    name: "proveedor",
    label: "Proveedor".toUpperCase(),
    field: "proveedor",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaEnvioAprobacion",
    label: "Fecha envío aprobación".toUpperCase(),
    field: "fechaEnvioAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaAprobacion",
    label: "Fecha aprobación".toUpperCase(),
    field: "fechaAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "diasGestionAprobacion",
    label: "Días en gestión de aprobación".toUpperCase(),
    field: "diasGestionAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "aprobador",
    label: "Aprobador".toUpperCase(),
    field: "aprobador",
    sortable: true,
    align: "center",
  },
  {
    name: "compromisosProximos",
    label: "Compromisos próximos".toUpperCase(),
    field: "compromisosProximos",
    sortable: true,
    align: "center",
  },
  {
    name: "nombreRemitente",
    label: "Nombre del remitente".toUpperCase(),
    field: "nombreRemitente",
    sortable: true,
    align: "center",
  },
  {
    name: "departamentoRemitente",
    label: "Departamento del remitente".toUpperCase(),
    field: "departamentoRemitente",
    sortable: true,
    align: "center",
  },
  {
    name: "municipioRemitente",
    label: "Municipio del remitente".toUpperCase(),
    field: "municipioRemitente",
    sortable: true,
    align: "center",
  },
  {
    name: "direccionRemitente",
    label: "Dirección del remitente".toUpperCase(),
    field: "direccionRemitente",
    sortable: true,
    align: "center",
  },
  {
    name: "correoRemitente",
    label: "Correo electrónico remitente".toUpperCase(),
    field: "correoRemitente",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoDocumentoAfectado",
    label: "Tipo documento afectado".toUpperCase(),
    field: "tipoDocumentoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "documentoAfectado",
    label: "Documento del afectado".toUpperCase(),
    field: "documentoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "nombreAfectado",
    label: "Nombre del afectado".toUpperCase(),
    field: "nombreAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "generoAfectado",
    label: "Género del afectado".toUpperCase(),
    field: "generoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "empresaAfectado",
    label: "Empresa del afectado".toUpperCase(),
    field: "empresaAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "direccionAfectado",
    label: "Dirección del afectado".toUpperCase(),
    field: "direccionAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "correoAfectado",
    label: "Correo electrónico del afectado".toUpperCase(),
    field: "correoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "telefonoAfectado",
    label: "Teléfono del afectado".toUpperCase(),
    field: "telefonoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "tiempoEnGestion",
    label: "Tiempo en gestión".toUpperCase(),
    field: "tiempoEnGestion",
    sortable: true,
    align: "center",
  },
  {
    name: "prefijo",
    label: "Prefijo".toUpperCase(),
    field: "prefijo",
    sortable: true,
    align: "center",
  },
  {
    name: "radicadoSalida",
    label: "Radicado de salida".toUpperCase(),
    field: "radicadoSalida",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRadicacionSalida",
    label: "Fecha radicación salida".toUpperCase(),
    field: "fechaRadicacionSalida",
    sortable: true,
    align: "center",
  },
  {
    name: "medioEnvio",
    label: "Medio de envío".toUpperCase(),
    field: "medioEnvio",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroGuia",
    label: "Número de guía".toUpperCase(),
    field: "numeroGuia",
    sortable: true,
    align: "center",
  },
  {
    name: "estadoSalida",
    label: "Estado de salida".toUpperCase(),
    field: "estadoSalida",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoDocumentoDestinatario",
    label: "Tipo de documento del destinatario".toUpperCase(),
    field: "tipoDocumentoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroDocumentoDestinatario",
    label: "Número de documento del destinatario".toUpperCase(),
    field: "numeroDocumentoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "nombreDestinatario",
    label: "Nombre del destinatario".toUpperCase(),
    field: "nombreDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "departamentoDestinatario",
    label: "Departamento del destinatario".toUpperCase(),
    field: "departamentoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "municipioDestinatario",
    label: "Municipio del destinatario".toUpperCase(),
    field: "municipioDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "direccionDestinatario",
    label: "Dirección del destinatario".toUpperCase(),
    field: "direccionDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "telefonoDestinatario",
    label: "Teléfono del destinatario".toUpperCase(),
    field: "telefonoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "correoDestinatario",
    label: "Correo electrónico del destinatario".toUpperCase(),
    field: "correoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "conCopia",
    label: "Con copia".toUpperCase(),
    field: "conCopia",
    sortable: true,
    align: "center",
  },
  {
    name: "enviadoCopia",
    label: "Enviado el con copia".toUpperCase(),
    field: "enviadoCopia",
    sortable: true,
    align: "center",
  },
  {
    name: "formaCopia",
    label: "Forma de envío de con copia".toUpperCase(),
    field: "formaCopia",
    sortable: true,
    align: "center",
  },
  {
    name: "formaDestinatarioCopia",
    label: "Forma de envío del destinatario de la copia".toUpperCase(),
    field: "formaDestinatarioCopia",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaEnvioRevision",
    label: "Fecha envío revisión".toUpperCase(),
    field: "fechaEnvioRevisio",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRevision",
    label: "Fecha revisión".toUpperCase(),
    field: "fechaRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "diasEnGestionDeRevision",
    label: "Días en gestión de revisión".toUpperCase(),
    field: "diasEnGestionDeRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "revisor",
    label: "Revisor".toUpperCase(),
    field: "revisor",
    sortable: true,
    align: "center",
  },
];

export const REPORTES_HEADER_DOCSAL = [
  {
    name: "idRadicado",
    label: "NÚMERO RADICADO",
    field: "idRadicado",
    sortable: true,
    align: "center",
  },
  {
    name: "copia",
    label: "COPIA",
    field: "copia",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRadicacionSalida",
    label: "FECHA RADICACIÓN",
    field: "fechaRadicacionSalida",
    sortable: true,
    align: "center",
  },
  {
    name: "mes",
    label: "MES",
    field: "mes",
    sortable: true,
    align: "center",
  },
  {
    name: "radicadoEntrada",
    label: "RADICADO ENTRADA",
    field: "radicadoEntrada",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRadicacionEntrada",
    label: "FECHA RADICACIÓN ENTRADA",
    field: "fechaRadicacionEntrada",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaMaximaRespuesta",
    label: "FECHA MÁXIMA RESPUESTA",
    field: "fechaMaximaRespuesta",
    sortable: true,
    align: "center",
  },
  {
    name: "radicadoAnterior",
    label: "RADICADO ANTERIOR",
    field: "radicadoAnterior",
    sortable: true,
    align: "center",
  },
  {
    name: "consecutivoCreacion",
    label: "CONSECUTIVO DE CREACIÓN",
    field: "consecutivoCreacion",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaCreacion",
    label: "FECHA CREACIÓN",
    field: "fechaCreacion",
    sortable: true,
    align: "center",
  },
  {
    name: "tramite",
    label: "TRÁMITE",
    field: "tramite",
    sortable: true,
    align: "center",
  },
  {
    name: "gestionador",
    label: "GESTIONADOR RESPONSABLE",
    field: "gestionador",
    sortable: true,
    align: "center",
  },
  {
    name: "oficina",
    label: "OFICINA",
    field: "oficina",
    sortable: true,
    align: "center",
  },
  {
    name: "radicador",
    label: "RADICADOR",
    field: "radicador",
    sortable: true,
    align: "center",
  },
  {
    name: "destinatario",
    label: "DESTINATARIO",
    field: "destinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoDocumento",
    label: "TIPO DOCUMENTO DESTINATARIO",
    field: "tipoDocumento",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroDocumento",
    label: "NÚMERO DOCUMENTO DESTINATARIO",
    field: "numeroDocumento",
    sortable: true,
    align: "center",
  },
  {
    name: "departamento",
    label: "DEPARTAMENTO DESTINATARIO",
    field: "departamento",
    sortable: true,
    align: "center",
  },
  {
    name: "municipio",
    label: "MUNICIPIO DESTINATARIO",
    field: "municipio",
    sortable: true,
    align: "center",
  },
  {
    name: "cantidadFolios",
    label: "CANTIDAD DE FOLIOS",
    field: "cantidadFolios",
    sortable: true,
    align: "center",
  },
  {
    name: "anexos",
    label: "ANEXOS",
    field: "anexos",
    sortable: true,
    align: "center",
  },
  {
    name: "prefijo",
    label: "PREFIJO",
    field: "prefijo",
    sortable: true,
    align: "center",
  },
  {
    name: "asunto",
    label: "ASUNTO",
    field: "asunto",
    sortable: true,
    align: "center",
  },
  {
    name: "estadoSalida",
    label: "ESTADO SALIDA",
    field: "estadoSalida",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoDocumentoAfectado",
    label: "TIPO DOCUMENTO AFECTADO",
    field: "tipoDocumentoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroDocumentoAfectado",
    label: "NUMERO DOCUMENTO AFECTADO",
    field: "numeroDocumentoAfectado",
    sortable: true,
    align: "center",
  },
  {
    name: "afectado",
    label: "NOMBRE AFECTADO",
    field: "afectado",
    sortable: true,
    align: "center",
  },
  {
    name: "empresa",
    label: "EMPRESA AFECTADO",
    field: "empresa",
    sortable: true,
    align: "center",
  },
  {
    name: "proceso",
    label: "PROCESO (ASISTENTE)",
    field: "proceso",
    sortable: true,
    align: "center",
  },
  {
    name: "subproceso",
    label: "SUBPROCESO",
    field: "subproceso",
    sortable: true,
    align: "center",
  },
  {
    name: "formatoTiempo",
    label: "FORMATO TIEMPO",
    field: "formatoTiempo",
    sortable: true,
    align: "center",
  },
  {
    name: "tiempoDefinido",
    label: "TIEMPO DEFINIDO",
    field: "tiempoDefinido",
    sortable: true,
    align: "center",
  },
  {
    name: "proveedor",
    label: "PROVEEDOR (GESTIONADOR)",
    field: "proveedor",
    sortable: true,
    align: "center",
  },
  {
    name: "compromisosProximos",
    label: "COMPROMISOS PRÓXIMOS",
    field: "compromisosProximos",
    sortable: true,
    align: "center",
  },
  {
    name: "descripcionCompromisosProximos",
    label: "DESCRIPCIÓN COMPROMISOS PRÓXIMOS",
    field: "descripcionCompromisosProximos",
    sortable: true,
    align: "center",
  },
  {
    name: "tipoEvento",
    label: "TIPO EVENTO",
    field: "tipoEvento",
    sortable: true,
    align: "center",
  },
  {
    name: "siniestro",
    label: "NÚMERO SINIESTRO",
    field: "siniestro",
    sortable: true,
    align: "center",
  },
  {
    name: "estadoSiniestro",
    label: "ESTADO SINIESTRO",
    field: "estadoSiniestro",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRechazoAprobacion",
    label: "FECHA DE RECHAZO DEL APROBADOR",
    field: "fechaRechazoAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "responsableRechazoAprobacion",
    label: "RESPONSABLE DE RECHAZO DE LA APROBACION",
    field: "responsableRechazoAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "motivoRechazoAprobacion",
    label: "MOTIVO DEL RECHAZO APROBACIÓN",
    field: "motivoRechazoAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroRechazosAprobacion",
    label: "NÚMERO RECHAZOS",
    field: "numeroRechazosAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "aprobacionMasiva",
    label: "APROBACIÓN MASIVA",
    field: "aprobacionMasiva",
    sortable: true,
    align: "center",
  },
  {
    name: "aprobador",
    label: "APROBADOR",
    field: "aprobador",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaEnvioAprobacion",
    label: "FECHA ENVÍO APROBACIÓN",
    field: "fechaEnvioAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaAprobacion",
    label: "FECHA APROBACIÓN",
    field: "fechaAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "diasEnAprobacion",
    label: "DÍAS EN APROBACIÓN",
    field: "diasEnAprobacion",
    sortable: true,
    align: "center",
  },
  {
    name: "estadoGuia",
    label: "ESTADO GUÍA",
    field: "estadoGuia",
    sortable: true,
    align: "center",
  },
  {
    name: "formaEnvio",
    label: "FORMA DE ENVÍO",
    field: "formaEnvio",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRecibidoCorrespondencia",
    label: "FECHA RECIBIDO CORRESPONDENCIA",
    field: "fechaRecibidoCorrespondencia",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroGuiaEnvio",
    label: "NÚMERO GUÍA ENVÍO",
    field: "numeroGuiaEnvio",
    sortable: true,
    align: "center",
  },
  {
    name: "correoDestinatario",
    label: "CORREO DESTINATARIO",
    field: "correoDestinatario",
    sortable: true,
    align: "center",
  },
  {
    name: "idEnvioCorreoElectronicoCertificado",
    label: "Id envío correo electrónico certificado".toUpperCase(),
    field: "idEnvioCorreoElectronicoCertificado",
    sortable: true,
    align: "center",
  },
  {
    name: "eventoCorreoElectronicoCertificado",
    label: "Evento correo electrónico certificado".toUpperCase(),
    field: "eventoCorreoElectronicoCertificado",
    sortable: true,
    align: "center",
  },
  {
    name: "cuentaEnviarCorreo",
    label: "CUENTA ENVIO CORREO",
    field: "cuentaEnviarCorreo",
    sortable: true,
    align: "center",
  },
  {
    name: "accionDevolucion",
    label: "ACCION DEVOLUCION",
    field: "accionDevolucion",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroGuiaEnvioDevolucion",
    label: "NUMERO GUIA ENVIO DEVOLUCION",
    field: "numeroGuiaEnvioDevolucion",
    sortable: true,
    align: "center",
  },
  {
    name: "correoDestinatarioDevolucion",
    label: "CORREO DESTINATARIO DEVOLUCION",
    field: "correoDestinatarioDevolucion",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroDevolucion",
    label: "NUMERO DEVOLUCION",
    field: "numeroDevolucion",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRechazoRevision",
    label: "FECHA DE RECHAZO DE REVISION",
    field: "fechaRechazoRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "responsableRechazoRevision",
    label: "RESPONSABLE DE RECHAZO DE LA REVISION",
    field: "responsableRechazoRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "motivoRechazoRevision",
    label: "MOTIVO DEL RECHAZO REVISIÓN",
    field: "motivoRechazoRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroRechazosRevision",
    label: "NUMERO RECHAZOS",
    field: "numeroRechazosRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "revisionMasiva",
    label: "REVISIÓN MASIVA",
    field: "revisionMasiva",
    sortable: true,
    align: "center",
  },
  {
    name: "revisor",
    label: "REVISOR",
    field: "revisor",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaEnvioRevision",
    label: "FECHA ENVÍO REVISIÓN",
    field: "fechaEnvioRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaRevision",
    label: "FECHA REVISIÓN",
    field: "fechaRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "diasEnRevision",
    label: "DÍAS EN REVISIÓN",
    field: "diasEnRevision",
    sortable: true,
    align: "center",
  },
  {
    name: "publicado",
    label: "Publicado".toUpperCase(),
    field: "publicado",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaPublicacion",
    label: "Fecha de publicación".toUpperCase(),
    field: "fechaPublicacion",
    sortable: true,
    align: "center",
  },
  {
    name: "numeroActaDesfijacion",
    label: "Número acta de desfijación".toUpperCase(),
    field: "numeroActaDesfijacion",
    sortable: true,
    align: "center",
  },
  {
    name: "fechaActaDesfijacion",
    label: "Fecha acta desfijación".toUpperCase(),
    field: "fechaActaDesfijacion",
    sortable: true,
    align: "center",
  },
  {
    name: "remitente",
    label: "REMITENTE",
    field: "remitente",
    sortable: true,
    align: "center",
  },
  {
    name: "correoRemitente",
    label: "CORREO REMITENTE",
    field: "correoRemitente",
    sortable: true,
    align: "center",
  },
];
