
export const COPIA_HEADER = [
  {
    name: "formaEnvio",
    align: "center",
    label: "Forma de Envío",
    field: "formaEnvio",
    sortable: true,
  },
  {
    name: "tipoDocumento",
    align: "center",
    label: "Tipo de Documento Destinatario",
    field: "tipoDocumento",
    sortable: true,
  },
  {
    name: "numeroDocumento",
    align: "center",
    label: "Número Documento Destinatario",
    field: "numeroDocumento",
    sortable: true,
  },
  {
    name: "nombre",
    align: "center",
    label: "Nombre del Destinatario",
    field: "nombre",
    sortable: true,
  },
  {
    name: "direccion",
    align: "center",
    label: "Dirección del Destinatario",
    field: "direccion",
    sortable: true,
  },
  {
    name: "pais",
    align: "center",
    label: "País Destinatario",
    field: "pais",
    sortable: true,
  },
  {
    name: "departamento",
    align: "center",
    label: "Departamento Destinatario",
    field: "departamento",
    sortable: true,
  },
  {
    name: "municipio",
    align: "center",
    label: "Municipio Destinatario",
    field: "municipio",
    sortable: true,
  },
  {
    name: "telefono",
    align: "center",
    label: "Teléfono Destinatario",
    field: "telefono",
    sortable: true,
  },
  {
    name: "correo",
    align: "center",
    label: "Correo Electrónico",
    field: "correo",
    sortable: true,
  },
  {
    name: "acciones",
    align: "center",
    label: "Acciones",
    field: "acciones",
  },
];

export const COPIA_HEADER2 = [
  {
    name: "formaEnvio",
    align: "center",
    label: "Forma de Envío",
    field: "formaEnvio",
    sortable: true,
  },
  {
    name: "tipoDocumentoDestinatario",
    align: "center",
    label: "Tipo de Documento Destinatario",
    field: "tipoDocumentoDestinatario",
    sortable: true,
  },
  {
    name: "numeroDocumentoDestinatario",
    align: "center",
    label: "Número documento destinatario",
    field: "numeroDocumentoDestinatario",
    sortable: true,
  },
  {
    name: "nombreDestinatario",
    align: "center",
    label: "Nombre del Destinatario",
    field: "nombreDestinatario",
    sortable: true,
  },
  {
    name: "direccionDestinatario",
    align: "center",
    label: "Dirección de Destinatario",
    field: "direccionDestinatario",
    sortable: true,
  },
  {
    name: "paisDestinatario",
    align: "center",
    label: "País Destinatario",
    field: "paisDestinatario",
    sortable: true,
  },
  {
    name: "departamentoDestinatario",
    align: "center",
    label: "Departamento Destinatario",
    field: "departamentoDestinatario",
    sortable: true,
  },
  {
    name: "municipioDestinatario",
    align: "center",
    label: "Municipio Destinatario",
    field: "municipioDestinatario",
    sortable: true,
  },
  {
    name: "telefonoDestinatario",
    align: "center",
    label: "Teléfono Destinatario",
    field: "telefonoDestinatario",
    sortable: true,
  },
  {
    name: "correoElectronico",
    align: "center",
    label: "Correo Electrónico",
    field: "correoElectronico",
    sortable: true,
  },
  {
    name: "acciones",
    align: "center",
    label: "Acciones",
    field: "acciones",
  },
];

export const COPIA_HEADER3 = [
  {
    name: "correspondenciaDependencia",
    align: "center",
    label: "Dependencia",
    field: "correspondenciaDependencia",
    sortable: true,
  },
  {
    name: "correspondenciaFuncionario",
    align: "center",
    label: "Nombre Funcionario",
    field: "correspondenciaFuncionario",
    sortable: true,
  },
  {
    name: "acciones",
    align: "center",
    label: "Acciones",
    field: "acciones",
    sortable: true,
  },
];
