export const GESTIONAR_BODY = [
  {
    canalRaDicacion: 'Mail',
    puntoRadicacion: 'Mail Sucursal Cundinamarca',
    noRadicadoSGDEA: 'ENT202506240033452',
    fechaRadicacion: '20/06/2025 4:31:24 p.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR2406202500981',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Puerto Carreño',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
  {
    canalRaDicacion: 'Ventanilla',
    puntoRadicacion: 'Ventanilla Oficina Positiva - Mitú',
    noRadicadoSGDEA: 'ENT20250624101345',
    fechaRadicacion: '24/06/2025 8:34:59 a.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR2406202523885',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Mitú',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
  {
    canalRaDicacion: 'Mail',
    puntoRadicacion: 'Mail Sucursal Bogotá',
    noRadicadoSGDEA: 'ENT20250624230900',
    fechaRadicacion: '24/06/2025 8:36:59 a.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR2406202587652',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Bogotá D.C.',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
  {
    canalRaDicacion: 'Mail',
    puntoRadicacion: 'Mail Sucursal Cundinamarca',
    noRadicadoSGDEA: 'ENT20250624501345',
    fechaRadicacion: '24/06/2025 8:02:59 a.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR240620250177',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Fuente de Oro',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
  {
    canalRaDicacion: 'Mail',
    puntoRadicacion: 'Mail Sucursal Cundinamarca',
    noRadicadoSGDEA: 'ENT20250624079984',
    fechaRadicacion: '24/06/2025 8:02:59 a.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR240620259923',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Madrid',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
  {
    canalRaDicacion: 'Mail',
    puntoRadicacion: 'Mail Sucursal Cundinamarca',
    noRadicadoSGDEA: 'ENT20250624079984',
    fechaRadicacion: '24/06/2025 8:02:59 a.m.',
    entidadRemitente: 'Ministerio del Trabajo',
    noRadicadoRemitente: 'MTR240620259923',
    notificacionPositiva: '20/06/2025 4:31:24 p.m.',
    municipio: 'Madrid',
    nombreAfectado: 'Daylin Dayana Heredia Rosas',
    tipoDocumentoAfectado: 'PEP',
    numeroDocumentoAfectado: '1029854732',
    trazabilidad: 'Trazabilidad',
    estado: 'Por gestionar',
  },
];
export const GESTIONAR_HEADER = [
  {
    name: 'canalRaDicacion',
    align: 'center',
    label: 'Canal de Radicación',
    field: 'canalRaDicacion',
    sortable: true,
  },
  {
    name: 'puntoRadicacion',
    align: 'center',
    label: 'Punto de Radicación',
    field: 'puntoRadicacion',
    sortable: true,
  },
  {
    name: 'noRadicadoSGDEA',
    align: 'center',
    label: 'No. Radicado SGDEA',
    field: 'noRadicadoSGDEA',
    sortable: true,
  },
  {
    name: 'fechaRadicacion',
    align: 'center',
    label: 'Fecha Radicación',
    field: 'fechaRadicacion',
    sortable: false,
  },
  {
    name: 'entidadRemitente',
    align: 'center',
    label: 'Entidad Remitente',
    field: 'entidadRemitente',
    sortable: true,
  },
  {
    name: 'noRadicadoRemitente',
    align: 'center',
    label: 'No. Radicado Remitente',
    field: 'noRadicadoRemitente',
    sortable: true,
  },
  {
    name: 'notificacionPositiva',
    align: 'center',
    label: 'Notificación Positiva',
    field: 'notificacionPositiva',
    sortable: false,
  },
  {
    name: 'municipio',
    align: 'center',
    label: 'Municipio',
    field: 'municipio',
    sortable: true,
  },
  {
    name: 'nombreAfectado',
    align: 'center',
    label: 'Nombre del afectado',
    field: 'nombreAfectado',
    sortable: true,
  },
  {
    name: 'tipoDocumentoAfectado',
    align: 'center',
    label: 'Tipo de documento del afectado',
    field: 'tipoDocumentoAfectado',
    sortable: true,
  },
  {
    name: 'numeroDocumentoAfectado',
    align: 'center',
    label: 'Número de documento del afectado',
    field: 'numeroDocumentoAfectado',
    sortable: true,
  },
  {
    name: 'trazabilidad',
    align: 'center',
    label: 'Trazabilidad',
    field: 'trazabilidad',
    sortable: false,
  },
  {
    name: 'estado',
    align: 'center',
    label: 'Estado',
    field: 'estado',
    sortable: true,
  },
  {
    name: 'acciones',
    align: 'center',
    label: 'Acciones',
    field: 'acciones',
    sortable: false,
  },
];
